### ISSUE TITLE
ImportError: No module named configparser

### ISSUE THREAD

**Issue by mycarevault** [pradeepvemulakonda/Snomed#4]
Hi Pradeep, 
I am encountering the below error: any solutions pls

:\Python27\python.exe E:/SNOMED-CT/NEO4J1/run_snomed_upload.py
Traceback (most recent call last):
  File "E:/SNOMED-CT/NEO4J1/run_snomed_upload.py", line 3, in <module>
    from config.read_config import SnomedConfig
  File "E:\SNOMED-CT\NEO4J1\config\read_config.py", line 1, in <module>
    import configparser
ImportError: No module named configparser

Process finished with exit code 1

**Comment by pradeepvemulakonda** [comment]
Hi,

You have to use Python 3.5. Please go through the wiki to setup the project in Pycharm(IntelliJ).  Also setup a virtual environment if you have Myrtle python installations.

**Comment by mycarevault** [comment]
Thanks for the quick reply: I did follow all the steps mentioned in the wiki. Now I am getting new issues

Traceback (most recent call last):
  File "C:\Users\sathish\SnomedENV\lib\site-packages\py2neo\database\__init__.py", line 318, in __new__
    inst = cls.__instances[key]
KeyError: (<class 'py2neo.database.Graph'>, <ServerAddress settings={'bolt_port': 7687, 'host': 'localhost'}>, 'data')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sathish\SnomedENV\lib\site-packages\py2neo\database\http.py", line 154, in get
    response = self.__base.get(headers=headers, redirect_limit=redirect_limit, **kwargs)
  File "C:\Users\sathish\SnomedENV\lib\site-packages\py2neo\packages\httpstream\http.py", line 966, in get
    return self.__get_or_head("GET", if_modified_since, headers, redirect_limit, **kwargs)
  File "C:\Users\sathish\SnomedENV\lib\site-packages\py2neo\packages\httpstream\http.py", line 943, in __get_or_head
    return rq.submit(redirect_limit=redirect_limit, **kwargs)
  File "C:\Users\sathish\SnomedENV\lib\site-packages\py2neo\packages\httpstream\http.py", line 452, in submit
    return Response.wrap(http, uri, self, rs, **response_kwargs)
  File "C:\Users\sathish\SnomedENV\lib\site-packages\py2neo\packages\httpstream\http.py", line 489, in wrap
    raise inst
py2neo.packages.httpstream.http.ClientError: 401 Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Snomed-master/run_snomed_upload.py", line 60, in <module>
    sp = SnomedConceptProcessor()
  File "D:\Snomed-master\neo4j\snomed_concept_processor.py", line 17, in __init__
    self.graph = Graph(super().graph_url)
  File "C:\Users\sathish\SnomedENV\lib\site-packages\py2neo\database\__init__.py", line 327, in __new__
    use_bolt = version_tuple(inst.__remote__.get().content["neo4j_version"]) >= (3,)
  File "C:\Users\sathish\SnomedENV\lib\site-packages\py2neo\database\http.py", line 157, in get
    raise Unauthorized(self.uri.string)
py2neo.database.status.Unauthorized: http://localhost:7474/db/data/

Process finished with exit code 1

**Comment by pradeepvemulakonda** [comment]
The error is becasue of credentials issue.
